// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package com.daocheng.core.model;

public final class Trade {
  private Trade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ContractOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string instrument = 1;
    /**
     * <code>required string instrument = 1;</code>
     */
    boolean hasInstrument();
    /**
     * <code>required string instrument = 1;</code>
     */
    java.lang.String getInstrument();
    /**
     * <code>required string instrument = 1;</code>
     */
    com.google.protobuf.ByteString
        getInstrumentBytes();

    // required int32 notional = 2;
    /**
     * <code>required int32 notional = 2;</code>
     */
    boolean hasNotional();
    /**
     * <code>required int32 notional = 2;</code>
     */
    int getNotional();
  }
  /**
   * Protobuf type {@code com.daocheng.core.model.Contract}
   */
  public static final class Contract extends
      com.google.protobuf.GeneratedMessage
      implements ContractOrBuilder {
    // Use Contract.newBuilder() to construct.
    private Contract(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Contract(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Contract defaultInstance;
    public static Contract getDefaultInstance() {
      return defaultInstance;
    }

    public Contract getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Contract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              instrument_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              notional_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Contract_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Contract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.daocheng.core.model.Trade.Contract.class, com.daocheng.core.model.Trade.Contract.Builder.class);
    }

    public static com.google.protobuf.Parser<Contract> PARSER =
        new com.google.protobuf.AbstractParser<Contract>() {
      public Contract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contract(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Contract> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string instrument = 1;
    public static final int INSTRUMENT_FIELD_NUMBER = 1;
    private java.lang.Object instrument_;
    /**
     * <code>required string instrument = 1;</code>
     */
    public boolean hasInstrument() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string instrument = 1;</code>
     */
    public java.lang.String getInstrument() {
      java.lang.Object ref = instrument_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instrument_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string instrument = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes() {
      java.lang.Object ref = instrument_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 notional = 2;
    public static final int NOTIONAL_FIELD_NUMBER = 2;
    private int notional_;
    /**
     * <code>required int32 notional = 2;</code>
     */
    public boolean hasNotional() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 notional = 2;</code>
     */
    public int getNotional() {
      return notional_;
    }

    private void initFields() {
      instrument_ = "";
      notional_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasInstrument()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNotional()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getInstrumentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, notional_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getInstrumentBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, notional_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.daocheng.core.model.Trade.Contract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Contract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.daocheng.core.model.Trade.Contract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.daocheng.core.model.Trade.Contract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.daocheng.core.model.Trade.Contract prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.daocheng.core.model.Contract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.daocheng.core.model.Trade.ContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Contract_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Contract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.daocheng.core.model.Trade.Contract.class, com.daocheng.core.model.Trade.Contract.Builder.class);
      }

      // Construct using com.daocheng.core.model.Trade.Contract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        instrument_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        notional_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Contract_descriptor;
      }

      public com.daocheng.core.model.Trade.Contract getDefaultInstanceForType() {
        return com.daocheng.core.model.Trade.Contract.getDefaultInstance();
      }

      public com.daocheng.core.model.Trade.Contract build() {
        com.daocheng.core.model.Trade.Contract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.daocheng.core.model.Trade.Contract buildPartial() {
        com.daocheng.core.model.Trade.Contract result = new com.daocheng.core.model.Trade.Contract(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instrument_ = instrument_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.notional_ = notional_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.daocheng.core.model.Trade.Contract) {
          return mergeFrom((com.daocheng.core.model.Trade.Contract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.daocheng.core.model.Trade.Contract other) {
        if (other == com.daocheng.core.model.Trade.Contract.getDefaultInstance()) return this;
        if (other.hasInstrument()) {
          bitField0_ |= 0x00000001;
          instrument_ = other.instrument_;
          onChanged();
        }
        if (other.hasNotional()) {
          setNotional(other.getNotional());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInstrument()) {
          
          return false;
        }
        if (!hasNotional()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.daocheng.core.model.Trade.Contract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.daocheng.core.model.Trade.Contract) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string instrument = 1;
      private java.lang.Object instrument_ = "";
      /**
       * <code>required string instrument = 1;</code>
       */
      public boolean hasInstrument() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string instrument = 1;</code>
       */
      public java.lang.String getInstrument() {
        java.lang.Object ref = instrument_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          instrument_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string instrument = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInstrumentBytes() {
        java.lang.Object ref = instrument_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instrument_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string instrument = 1;</code>
       */
      public Builder setInstrument(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        instrument_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string instrument = 1;</code>
       */
      public Builder clearInstrument() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instrument_ = getDefaultInstance().getInstrument();
        onChanged();
        return this;
      }
      /**
       * <code>required string instrument = 1;</code>
       */
      public Builder setInstrumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        instrument_ = value;
        onChanged();
        return this;
      }

      // required int32 notional = 2;
      private int notional_ ;
      /**
       * <code>required int32 notional = 2;</code>
       */
      public boolean hasNotional() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 notional = 2;</code>
       */
      public int getNotional() {
        return notional_;
      }
      /**
       * <code>required int32 notional = 2;</code>
       */
      public Builder setNotional(int value) {
        bitField0_ |= 0x00000002;
        notional_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 notional = 2;</code>
       */
      public Builder clearNotional() {
        bitField0_ = (bitField0_ & ~0x00000002);
        notional_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.daocheng.core.model.Contract)
    }

    static {
      defaultInstance = new Contract(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.daocheng.core.model.Contract)
  }

  public interface TransactionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.daocheng.core.model.Contract contract = 1;
    /**
     * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
     */
    boolean hasContract();
    /**
     * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
     */
    com.daocheng.core.model.Trade.Contract getContract();
    /**
     * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
     */
    com.daocheng.core.model.Trade.ContractOrBuilder getContractOrBuilder();

    // required string counterparty = 2;
    /**
     * <code>required string counterparty = 2;</code>
     */
    boolean hasCounterparty();
    /**
     * <code>required string counterparty = 2;</code>
     */
    java.lang.String getCounterparty();
    /**
     * <code>required string counterparty = 2;</code>
     */
    com.google.protobuf.ByteString
        getCounterpartyBytes();
  }
  /**
   * Protobuf type {@code com.daocheng.core.model.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage
      implements TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.daocheng.core.model.Trade.Contract.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = contract_.toBuilder();
              }
              contract_ = input.readMessage(com.daocheng.core.model.Trade.Contract.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contract_);
                contract_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              counterparty_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.daocheng.core.model.Trade.Transaction.class, com.daocheng.core.model.Trade.Transaction.Builder.class);
    }

    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.daocheng.core.model.Contract contract = 1;
    public static final int CONTRACT_FIELD_NUMBER = 1;
    private com.daocheng.core.model.Trade.Contract contract_;
    /**
     * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
     */
    public boolean hasContract() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
     */
    public com.daocheng.core.model.Trade.Contract getContract() {
      return contract_;
    }
    /**
     * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
     */
    public com.daocheng.core.model.Trade.ContractOrBuilder getContractOrBuilder() {
      return contract_;
    }

    // required string counterparty = 2;
    public static final int COUNTERPARTY_FIELD_NUMBER = 2;
    private java.lang.Object counterparty_;
    /**
     * <code>required string counterparty = 2;</code>
     */
    public boolean hasCounterparty() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string counterparty = 2;</code>
     */
    public java.lang.String getCounterparty() {
      java.lang.Object ref = counterparty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          counterparty_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string counterparty = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCounterpartyBytes() {
      java.lang.Object ref = counterparty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        counterparty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      contract_ = com.daocheng.core.model.Trade.Contract.getDefaultInstance();
      counterparty_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContract()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCounterparty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getContract().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, contract_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCounterpartyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contract_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCounterpartyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.daocheng.core.model.Trade.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.daocheng.core.model.Trade.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.daocheng.core.model.Trade.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.daocheng.core.model.Trade.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.daocheng.core.model.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.daocheng.core.model.Trade.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.daocheng.core.model.Trade.Transaction.class, com.daocheng.core.model.Trade.Transaction.Builder.class);
      }

      // Construct using com.daocheng.core.model.Trade.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContractFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (contractBuilder_ == null) {
          contract_ = com.daocheng.core.model.Trade.Contract.getDefaultInstance();
        } else {
          contractBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        counterparty_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Transaction_descriptor;
      }

      public com.daocheng.core.model.Trade.Transaction getDefaultInstanceForType() {
        return com.daocheng.core.model.Trade.Transaction.getDefaultInstance();
      }

      public com.daocheng.core.model.Trade.Transaction build() {
        com.daocheng.core.model.Trade.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.daocheng.core.model.Trade.Transaction buildPartial() {
        com.daocheng.core.model.Trade.Transaction result = new com.daocheng.core.model.Trade.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (contractBuilder_ == null) {
          result.contract_ = contract_;
        } else {
          result.contract_ = contractBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.counterparty_ = counterparty_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.daocheng.core.model.Trade.Transaction) {
          return mergeFrom((com.daocheng.core.model.Trade.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.daocheng.core.model.Trade.Transaction other) {
        if (other == com.daocheng.core.model.Trade.Transaction.getDefaultInstance()) return this;
        if (other.hasContract()) {
          mergeContract(other.getContract());
        }
        if (other.hasCounterparty()) {
          bitField0_ |= 0x00000002;
          counterparty_ = other.counterparty_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContract()) {
          
          return false;
        }
        if (!hasCounterparty()) {
          
          return false;
        }
        if (!getContract().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.daocheng.core.model.Trade.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.daocheng.core.model.Trade.Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.daocheng.core.model.Contract contract = 1;
      private com.daocheng.core.model.Trade.Contract contract_ = com.daocheng.core.model.Trade.Contract.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.daocheng.core.model.Trade.Contract, com.daocheng.core.model.Trade.Contract.Builder, com.daocheng.core.model.Trade.ContractOrBuilder> contractBuilder_;
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public boolean hasContract() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public com.daocheng.core.model.Trade.Contract getContract() {
        if (contractBuilder_ == null) {
          return contract_;
        } else {
          return contractBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public Builder setContract(com.daocheng.core.model.Trade.Contract value) {
        if (contractBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contract_ = value;
          onChanged();
        } else {
          contractBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public Builder setContract(
          com.daocheng.core.model.Trade.Contract.Builder builderForValue) {
        if (contractBuilder_ == null) {
          contract_ = builderForValue.build();
          onChanged();
        } else {
          contractBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public Builder mergeContract(com.daocheng.core.model.Trade.Contract value) {
        if (contractBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              contract_ != com.daocheng.core.model.Trade.Contract.getDefaultInstance()) {
            contract_ =
              com.daocheng.core.model.Trade.Contract.newBuilder(contract_).mergeFrom(value).buildPartial();
          } else {
            contract_ = value;
          }
          onChanged();
        } else {
          contractBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public Builder clearContract() {
        if (contractBuilder_ == null) {
          contract_ = com.daocheng.core.model.Trade.Contract.getDefaultInstance();
          onChanged();
        } else {
          contractBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public com.daocheng.core.model.Trade.Contract.Builder getContractBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getContractFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      public com.daocheng.core.model.Trade.ContractOrBuilder getContractOrBuilder() {
        if (contractBuilder_ != null) {
          return contractBuilder_.getMessageOrBuilder();
        } else {
          return contract_;
        }
      }
      /**
       * <code>required .com.daocheng.core.model.Contract contract = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.daocheng.core.model.Trade.Contract, com.daocheng.core.model.Trade.Contract.Builder, com.daocheng.core.model.Trade.ContractOrBuilder> 
          getContractFieldBuilder() {
        if (contractBuilder_ == null) {
          contractBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.daocheng.core.model.Trade.Contract, com.daocheng.core.model.Trade.Contract.Builder, com.daocheng.core.model.Trade.ContractOrBuilder>(
                  contract_,
                  getParentForChildren(),
                  isClean());
          contract_ = null;
        }
        return contractBuilder_;
      }

      // required string counterparty = 2;
      private java.lang.Object counterparty_ = "";
      /**
       * <code>required string counterparty = 2;</code>
       */
      public boolean hasCounterparty() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string counterparty = 2;</code>
       */
      public java.lang.String getCounterparty() {
        java.lang.Object ref = counterparty_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          counterparty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string counterparty = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCounterpartyBytes() {
        java.lang.Object ref = counterparty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          counterparty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string counterparty = 2;</code>
       */
      public Builder setCounterparty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        counterparty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string counterparty = 2;</code>
       */
      public Builder clearCounterparty() {
        bitField0_ = (bitField0_ & ~0x00000002);
        counterparty_ = getDefaultInstance().getCounterparty();
        onChanged();
        return this;
      }
      /**
       * <code>required string counterparty = 2;</code>
       */
      public Builder setCounterpartyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        counterparty_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.daocheng.core.model.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.daocheng.core.model.Transaction)
  }

  public interface PortfolioOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.daocheng.core.model.Transaction transaction = 1;
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    java.util.List<com.daocheng.core.model.Trade.Transaction> 
        getTransactionList();
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    com.daocheng.core.model.Trade.Transaction getTransaction(int index);
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    int getTransactionCount();
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    java.util.List<? extends com.daocheng.core.model.Trade.TransactionOrBuilder> 
        getTransactionOrBuilderList();
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    com.daocheng.core.model.Trade.TransactionOrBuilder getTransactionOrBuilder(
        int index);

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.daocheng.core.model.Portfolio}
   */
  public static final class Portfolio extends
      com.google.protobuf.GeneratedMessage
      implements PortfolioOrBuilder {
    // Use Portfolio.newBuilder() to construct.
    private Portfolio(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Portfolio(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Portfolio defaultInstance;
    public static Portfolio getDefaultInstance() {
      return defaultInstance;
    }

    public Portfolio getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Portfolio(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                transaction_ = new java.util.ArrayList<com.daocheng.core.model.Trade.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              transaction_.add(input.readMessage(com.daocheng.core.model.Trade.Transaction.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          transaction_ = java.util.Collections.unmodifiableList(transaction_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Portfolio_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Portfolio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.daocheng.core.model.Trade.Portfolio.class, com.daocheng.core.model.Trade.Portfolio.Builder.class);
    }

    public static com.google.protobuf.Parser<Portfolio> PARSER =
        new com.google.protobuf.AbstractParser<Portfolio>() {
      public Portfolio parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Portfolio(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Portfolio> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .com.daocheng.core.model.Transaction transaction = 1;
    public static final int TRANSACTION_FIELD_NUMBER = 1;
    private java.util.List<com.daocheng.core.model.Trade.Transaction> transaction_;
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    public java.util.List<com.daocheng.core.model.Trade.Transaction> getTransactionList() {
      return transaction_;
    }
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    public java.util.List<? extends com.daocheng.core.model.Trade.TransactionOrBuilder> 
        getTransactionOrBuilderList() {
      return transaction_;
    }
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    public int getTransactionCount() {
      return transaction_.size();
    }
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    public com.daocheng.core.model.Trade.Transaction getTransaction(int index) {
      return transaction_.get(index);
    }
    /**
     * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
     */
    public com.daocheng.core.model.Trade.TransactionOrBuilder getTransactionOrBuilder(
        int index) {
      return transaction_.get(index);
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      transaction_ = java.util.Collections.emptyList();
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTransactionCount(); i++) {
        if (!getTransaction(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < transaction_.size(); i++) {
        output.writeMessage(1, transaction_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transaction_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transaction_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.daocheng.core.model.Trade.Portfolio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.daocheng.core.model.Trade.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.daocheng.core.model.Trade.Portfolio prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.daocheng.core.model.Portfolio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.daocheng.core.model.Trade.PortfolioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Portfolio_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Portfolio_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.daocheng.core.model.Trade.Portfolio.class, com.daocheng.core.model.Trade.Portfolio.Builder.class);
      }

      // Construct using com.daocheng.core.model.Trade.Portfolio.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTransactionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (transactionBuilder_ == null) {
          transaction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transactionBuilder_.clear();
        }
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.daocheng.core.model.Trade.internal_static_com_daocheng_core_model_Portfolio_descriptor;
      }

      public com.daocheng.core.model.Trade.Portfolio getDefaultInstanceForType() {
        return com.daocheng.core.model.Trade.Portfolio.getDefaultInstance();
      }

      public com.daocheng.core.model.Trade.Portfolio build() {
        com.daocheng.core.model.Trade.Portfolio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.daocheng.core.model.Trade.Portfolio buildPartial() {
        com.daocheng.core.model.Trade.Portfolio result = new com.daocheng.core.model.Trade.Portfolio(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (transactionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            transaction_ = java.util.Collections.unmodifiableList(transaction_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transaction_ = transaction_;
        } else {
          result.transaction_ = transactionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.daocheng.core.model.Trade.Portfolio) {
          return mergeFrom((com.daocheng.core.model.Trade.Portfolio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.daocheng.core.model.Trade.Portfolio other) {
        if (other == com.daocheng.core.model.Trade.Portfolio.getDefaultInstance()) return this;
        if (transactionBuilder_ == null) {
          if (!other.transaction_.isEmpty()) {
            if (transaction_.isEmpty()) {
              transaction_ = other.transaction_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransactionIsMutable();
              transaction_.addAll(other.transaction_);
            }
            onChanged();
          }
        } else {
          if (!other.transaction_.isEmpty()) {
            if (transactionBuilder_.isEmpty()) {
              transactionBuilder_.dispose();
              transactionBuilder_ = null;
              transaction_ = other.transaction_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transactionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTransactionFieldBuilder() : null;
            } else {
              transactionBuilder_.addAllMessages(other.transaction_);
            }
          }
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getTransactionCount(); i++) {
          if (!getTransaction(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.daocheng.core.model.Trade.Portfolio parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.daocheng.core.model.Trade.Portfolio) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.daocheng.core.model.Transaction transaction = 1;
      private java.util.List<com.daocheng.core.model.Trade.Transaction> transaction_ =
        java.util.Collections.emptyList();
      private void ensureTransactionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          transaction_ = new java.util.ArrayList<com.daocheng.core.model.Trade.Transaction>(transaction_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.daocheng.core.model.Trade.Transaction, com.daocheng.core.model.Trade.Transaction.Builder, com.daocheng.core.model.Trade.TransactionOrBuilder> transactionBuilder_;

      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public java.util.List<com.daocheng.core.model.Trade.Transaction> getTransactionList() {
        if (transactionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transaction_);
        } else {
          return transactionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public int getTransactionCount() {
        if (transactionBuilder_ == null) {
          return transaction_.size();
        } else {
          return transactionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public com.daocheng.core.model.Trade.Transaction getTransaction(int index) {
        if (transactionBuilder_ == null) {
          return transaction_.get(index);
        } else {
          return transactionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder setTransaction(
          int index, com.daocheng.core.model.Trade.Transaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionIsMutable();
          transaction_.set(index, value);
          onChanged();
        } else {
          transactionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder setTransaction(
          int index, com.daocheng.core.model.Trade.Transaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder addTransaction(com.daocheng.core.model.Trade.Transaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionIsMutable();
          transaction_.add(value);
          onChanged();
        } else {
          transactionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder addTransaction(
          int index, com.daocheng.core.model.Trade.Transaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionIsMutable();
          transaction_.add(index, value);
          onChanged();
        } else {
          transactionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder addTransaction(
          com.daocheng.core.model.Trade.Transaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.add(builderForValue.build());
          onChanged();
        } else {
          transactionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder addTransaction(
          int index, com.daocheng.core.model.Trade.Transaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder addAllTransaction(
          java.lang.Iterable<? extends com.daocheng.core.model.Trade.Transaction> values) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          super.addAll(values, transaction_);
          onChanged();
        } else {
          transactionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder clearTransaction() {
        if (transactionBuilder_ == null) {
          transaction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transactionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public Builder removeTransaction(int index) {
        if (transactionBuilder_ == null) {
          ensureTransactionIsMutable();
          transaction_.remove(index);
          onChanged();
        } else {
          transactionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public com.daocheng.core.model.Trade.Transaction.Builder getTransactionBuilder(
          int index) {
        return getTransactionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public com.daocheng.core.model.Trade.TransactionOrBuilder getTransactionOrBuilder(
          int index) {
        if (transactionBuilder_ == null) {
          return transaction_.get(index);  } else {
          return transactionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public java.util.List<? extends com.daocheng.core.model.Trade.TransactionOrBuilder> 
           getTransactionOrBuilderList() {
        if (transactionBuilder_ != null) {
          return transactionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transaction_);
        }
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public com.daocheng.core.model.Trade.Transaction.Builder addTransactionBuilder() {
        return getTransactionFieldBuilder().addBuilder(
            com.daocheng.core.model.Trade.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public com.daocheng.core.model.Trade.Transaction.Builder addTransactionBuilder(
          int index) {
        return getTransactionFieldBuilder().addBuilder(
            index, com.daocheng.core.model.Trade.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .com.daocheng.core.model.Transaction transaction = 1;</code>
       */
      public java.util.List<com.daocheng.core.model.Trade.Transaction.Builder> 
           getTransactionBuilderList() {
        return getTransactionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.daocheng.core.model.Trade.Transaction, com.daocheng.core.model.Trade.Transaction.Builder, com.daocheng.core.model.Trade.TransactionOrBuilder> 
          getTransactionFieldBuilder() {
        if (transactionBuilder_ == null) {
          transactionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.daocheng.core.model.Trade.Transaction, com.daocheng.core.model.Trade.Transaction.Builder, com.daocheng.core.model.Trade.TransactionOrBuilder>(
                  transaction_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          transaction_ = null;
        }
        return transactionBuilder_;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.daocheng.core.model.Portfolio)
    }

    static {
      defaultInstance = new Portfolio(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.daocheng.core.model.Portfolio)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_daocheng_core_model_Contract_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_daocheng_core_model_Contract_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_daocheng_core_model_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_daocheng_core_model_Transaction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_daocheng_core_model_Portfolio_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_daocheng_core_model_Portfolio_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013trade.proto\022\027com.daocheng.core.model\"0" +
      "\n\010Contract\022\022\n\ninstrument\030\001 \002(\t\022\020\n\010notion" +
      "al\030\002 \002(\005\"X\n\013Transaction\0223\n\010contract\030\001 \002(" +
      "\0132!.com.daocheng.core.model.Contract\022\024\n\014" +
      "counterparty\030\002 \002(\t\"T\n\tPortfolio\0229\n\013trans" +
      "action\030\001 \003(\0132$.com.daocheng.core.model.T" +
      "ransaction\022\014\n\004name\030\002 \002(\tB\031\n\027com.daocheng" +
      ".core.model"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_daocheng_core_model_Contract_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_daocheng_core_model_Contract_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_daocheng_core_model_Contract_descriptor,
              new java.lang.String[] { "Instrument", "Notional", });
          internal_static_com_daocheng_core_model_Transaction_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_daocheng_core_model_Transaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_daocheng_core_model_Transaction_descriptor,
              new java.lang.String[] { "Contract", "Counterparty", });
          internal_static_com_daocheng_core_model_Portfolio_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_daocheng_core_model_Portfolio_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_daocheng_core_model_Portfolio_descriptor,
              new java.lang.String[] { "Transaction", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
